# Generated by Django 2.1 on 2018-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=64, unique=True, verbose_name='歌曲ID')),
                ('song_name', models.CharField(max_length=100, verbose_name='歌曲名字')),
                ('song_pl_id', models.CharField(max_length=64, verbose_name='专辑ID')),
                ('song_publish_time', models.DateTimeField(blank=True, verbose_name='出版时间')),
                ('song_sing_id', models.CharField(max_length=100, verbose_name='歌手ID')),
                ('song_total_comments', models.IntegerField(blank=True, verbose_name='歌曲总的评论数')),
                ('song_hot_comments', models.IntegerField(blank=True, verbose_name='歌曲热门评论数')),
                ('song_url', models.CharField(blank=True, max_length=1000, verbose_name='歌曲链接')),
                ('song_lysic', models.TextField(blank=True, verbose_name='歌词')),
            ],
            options={
                'verbose_name_plural': '歌曲信息',
                'db_table': 'song',
            },
        ),
    ]
