# Generated by Django 2.1 on 2018-12-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20181224_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='歌曲名字'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_pl_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='专辑ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_sing_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='歌手ID'),
        ),
    ]
