# Generated by Django 2.1 on 2019-01-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20181227_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=64, unique=True, verbose_name='歌曲ID')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='歌曲标签')),
            ],
            options={
                'verbose_name_plural': '歌曲标签',
                'db_table': 'SongTag',
            },
        ),
    ]
