# Generated by Django 2.1 on 2019-01-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_songtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songtag',
            name='song_id',
            field=models.CharField(max_length=64, verbose_name='歌曲ID'),
        ),
    ]
