# Generated by Django 2.1 on 2019-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20190101_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=64, verbose_name='歌曲ID')),
                ('sim_song_id', models.CharField(blank=True, max_length=64, verbose_name='相似歌曲ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '歌曲相似',
                'db_table': 'SongSim',
            },
        ),
    ]
