# Generated by Django 2.1 on 2018-12-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_id', models.CharField(max_length=64, unique=True, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=64, verbose_name='名字')),
            ],
            options={
                'verbose_name_plural': '导航栏',
                'db_table': 'cate',
            },
        ),
    ]
