# Generated by Django 2.1 on 2018-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('click_id', models.CharField(max_length=64, verbose_name='ID')),
                ('click_cate', models.CharField(max_length=64, verbose_name='类别')),
                ('user_click_time', models.DateTimeField(verbose_name='浏览时间')),
            ],
            options={
                'verbose_name_plural': '用户行为信息',
                'db_table': 'UserBrowse',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='u_birthday',
            field=models.DateTimeField(blank=True, verbose_name='生日'),
        ),
    ]
