# Generated by Django 2.1 on 2019-01-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrowse',
            name='desc',
            field=models.CharField(default='Are you ready!', max_length=1000, verbose_name='备注'),
        ),
    ]
