# Generated by Django 2.1 on 2019-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userbrowse_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrowse',
            name='click_cate',
            field=models.CharField(blank=True, max_length=64, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='userbrowse',
            name='click_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbrowse',
            name='desc',
            field=models.CharField(blank=True, default='Are you ready!', max_length=1000, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='userbrowse',
            name='user_click_time',
            field=models.DateTimeField(blank=True, verbose_name='浏览时间'),
        ),
    ]
