# Generated by Django 2.1 on 2019-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190101_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('sim_user_id', models.CharField(blank=True, max_length=64, verbose_name='相似用户ID')),
                ('sim', models.FloatField(blank=True, verbose_name='用户相似度')),
            ],
            options={
                'verbose_name_plural': '用户相似',
                'db_table': 'UserSim',
            },
        ),
    ]
