# Generated by Django 2.1 on 2018-12-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_id', models.CharField(max_length=64, unique=True, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=64, verbose_name='歌单名字')),
                ('pl_create_time', models.DateTimeField(blank=True, verbose_name='创建时间')),
                ('pl_update_time', models.DateTimeField(blank=True, verbose_name='更新时间')),
                ('pl_songs_num', models.IntegerField(blank=True, verbose_name='包含音乐数')),
                ('pl_listen_num', models.IntegerField(blank=True, verbose_name='播放次数')),
                ('pl_share_num', models.IntegerField(blank=True, verbose_name='分享次数')),
                ('pl_comment_num', models.IntegerField(blank=True, verbose_name='评论次数')),
                ('pl_follow_num', models.IntegerField(blank=True, verbose_name='收藏次数')),
                ('pl_tags', models.CharField(blank=True, max_length=1000, verbose_name='歌单标签')),
                ('pl_img_url', models.CharField(blank=True, max_length=1000, verbose_name='歌单封面')),
                ('pl_desc', models.TextField(blank=True, verbose_name='歌单描述')),
                ('pl_creator', models.ForeignKey(on_delete=False, related_name='创建者信息', to='user.User')),
            ],
            options={
                'verbose_name_plural': '歌单信息',
                'db_table': 'playList',
            },
        ),
    ]
