# Generated by Django 2.1 on 2018-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListToSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_id', models.ForeignKey(on_delete=False, related_name='歌单ID', to='playlist.PlayList')),
                ('song_id', models.ForeignKey(on_delete=False, related_name='歌曲ID', to='song.Song')),
            ],
            options={
                'verbose_name_plural': '歌曲所属歌单',
                'db_table': 'playListToSongs',
            },
        ),
    ]
