# Generated by Django 2.1 on 2018-12-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlisttosongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttosongs',
            name='pl_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='歌单ID'),
        ),
        migrations.AlterField(
            model_name='playlisttosongs',
            name='song_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='歌曲ID'),
        ),
    ]
