# Generated by Django 2.1 on 2018-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing_id', models.CharField(max_length=64, unique=True, verbose_name='歌手ID')),
                ('sing_name', models.CharField(max_length=100, verbose_name='歌手名字')),
                ('sing_music_num', models.IntegerField(verbose_name='音乐数目')),
                ('sing_mv_num', models.IntegerField(verbose_name='MV数目')),
                ('sing_album_num', models.IntegerField(verbose_name='专辑数目')),
                ('sing_url', models.CharField(blank=True, max_length=1000, verbose_name='歌手图片')),
            ],
            options={
                'verbose_name_plural': '歌手信息',
                'db_table': 'sing',
            },
        ),
    ]
