# Generated by Django 2.1 on 2018-12-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sing',
            name='sing_album_num',
            field=models.IntegerField(blank=True, verbose_name='专辑数目'),
        ),
        migrations.AlterField(
            model_name='sing',
            name='sing_music_num',
            field=models.IntegerField(blank=True, verbose_name='音乐数目'),
        ),
        migrations.AlterField(
            model_name='sing',
            name='sing_mv_num',
            field=models.IntegerField(blank=True, verbose_name='MV数目'),
        ),
    ]
