# Generated by Django 2.1 on 2018-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0002_auto_20181223_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sing',
            name='sing_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='歌手名字'),
        ),
    ]
