# Generated by Django 2.1 on 2019-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0005_auto_20190101_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing_id', models.CharField(blank=True, max_length=64, verbose_name='歌手ID')),
                ('sim_sing_id', models.CharField(blank=True, max_length=64, verbose_name='相似歌手ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '歌手相似',
                'db_table': 'SingSim',
            },
        ),
    ]
